name: Build Data

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v1

            - name: Setup Deno 🚧
              uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.12.X

            - name: Build data 🔧
              run: |
                  deno run -A --import-map=importMap.json ./scripts/build.ts

            - name: Commit files ✅
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A && git commit -m "Updated extensions"

            - name: Push changes 🔼
              uses: ad-m/github-push-action@master
              with:
                  branch: main
                  github_token: ${{ secrets.GITHUB_TOKEN }}
